START TRANSACTION;

CREATE TABLE IF NOT EXISTS _logs (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `level` INT NOT NULL DEFAULT 0,
    `message` TEXT NOT NULL DEFAULT "",
    `data` JSON NOT NULL DEFAULT "{}",
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS _tables (
    `id` CHAR(36) NOT NULL DEFAULT UUID() PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `system` BOOLEAN NOT NULL DEFAULT 0,
    `module` VARCHAR(255),
    -- listRule createRule etc
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uc__tables_name UNIQUE (`name`)
);
CREATE TABLE IF NOT EXISTS _fields (
    `id` CHAR(36) NOT NULL DEFAULT UUID() PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL DEFAULT "",
    `table` CHAR(36) NOT NULL,
    `system` BOOLEAN NOT NULL DEFAULT 0,
    `module` VARCHAR(255),
    `type` ENUM("BOOLEAN", "CHAR", "VARCHAR", "TEXT", "DATETIME", "TIMESTAMP", "INT", "JSON", "FLOAT") NOT NULL,
    `size` INT,
    `nullable` BOOLEAN NOT NULL DEFAULT 0,
    `primary` BOOLEAN NOT NULL DEFAULT 0,
    `default` TEXT,
    `foreignKey` JSON,
    `unique` BOOLEAN NOT NULL DEFAULT 0,
    `index` BOOLEAN NOT NULL DEFAULT 0,
	`autoIncrement` BOOLEAN NOT NULL DEFAULT 0,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk__fields_tables FOREIGN KEY (`table`) REFERENCES `_tables`(`id`)
);

COMMIT;